/*---------------------------------------------------------
  The options statement below should be placed
  before the data step when submitting this code.
---------------------------------------------------------*/
options VALIDMEMNAME=EXTEND VALIDVARNAME=ANY;
   /*------------------------------------------
   Generated SAS Scoring Code
     Date             : 13Oct2022:19:06:09
     Locale           : en_US
     Model Type       : Decision Tree
     Interval variable: PolicyNumber
     Class variable   : BasePolicy
     Class variable   : PolicyType
     Class variable   : VehicleCategory
     Class variable   : Fault
     Class variable   : VehiclePrice
     Class variable   : PastNumberOfClaims
     Class variable   : Make
     Class variable   : Month
     Class variable   : AgeOfVehicle
     Class variable   : AgeOfPolicyHolder
     Class variable   : NumberOfSuppliments
     Class variable   : AccidentArea
     Class variable   : MonthClaimed
     Class variable   : Sex
     Class variable   : DayOfWeek
     Class variable   : DayOfWeekClaimed
     Class variable   : FraudFound
     Response variable: FraudFound
     ------------------------------------------*/
   /*---------------------------------------------------------
   SAS Code Generated by Cloud Analytic Services for Decision Tree
     Date                  : 13Oct2022:23:06:09 UTC
     Number of Nodes       : 9
     Number of Tree Depth  : 5
     Number of Bins        : 50
     Number of Obs         : 1846
     -------------------------------------------------------*/

   length _strfmt_ $20; drop _strfmt_;
   _strfmt_ = ' ';

   array _tlevname_17134_{2} $3 _temporary_ ( 'No' 
   'Yes');

   array _dt_fi_17134_{2} _temporary_;

   _node_id_ =  0;
   _new_id_  = -1;
   nextnode_17134:
   if _node_id_ eq 0 then do;
         _numval_ = PolicyNumber;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 14085.44 and _numval_ lt 15420) then do;

            _new_id_ = 1;
         end;
         else if (_numval_ ge 29 and _numval_ lt 14085.44) then do;

            _new_id_ = 2;
         end;
         else if (_numval_ lt 29) then do;
            _new_id_ = 2;
         end;
         else if (_numval_ ge 15420) then do;
            _new_id_ = 1;
         end;
         else do;
         _new_id_ = 1;
         end;
   end;
   else if _node_id_ eq 1 then do;
         _strfmt_ = left(trim(put(Month,$3.)));
         if _strfmt_ in ('Dec',
         'Apr',
         'May',
         'Mar',
         'Feb',
         'Jul',
         'Jun',
         'Jan') then do;

         _new_id_ = 3;
         end;
         else if _strfmt_ in ('Aug',
         'Nov',
         'Oct',
         'Sep') then do;

         _new_id_ = 4;
         end;
         else do;
         _new_id_ = 3;
         end;
   end;
   else if _node_id_ eq 2 then do;
         _leaf_id_ = 2;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =                    1;
         _dt_fi_17134_{1} =                    0; 
         _dt_fi_17134_{2} =                    1; 
   end;
   else if _node_id_ eq 3 then do;
         _leaf_id_ = 3;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.99466192170818;
         _dt_fi_17134_{1} =     0.99466192170818; 
         _dt_fi_17134_{2} =     0.00533807829181; 
   end;
   else if _node_id_ eq 4 then do;
         _numval_ = PolicyNumber;
         if missing(_numval_) then do;
            _numval_ = -1.7976931348623E308;
         end;
         if (_numval_ ge 14459.08 and _numval_ lt 15420) then do;

            _new_id_ = 5;
         end;
         else if (_numval_ ge 29 and _numval_ lt 14459.08) then do;

            _new_id_ = 6;
         end;
         else if (_numval_ lt 29) then do;
            _new_id_ = 6;
         end;
         else if (_numval_ ge 15420) then do;
            _new_id_ = 5;
         end;
         else do;
         _new_id_ = 5;
         end;
   end;
   else if _node_id_ eq 5 then do;
         _leaf_id_ = 5;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.87901234567901;
         _dt_fi_17134_{1} =     0.87901234567901; 
         _dt_fi_17134_{2} =     0.12098765432098; 
   end;
   else if _node_id_ eq 6 then do;
         _strfmt_ = left(trim(put(Month,$3.)));
         if _strfmt_ in ('Nov',
         'Oct') then do;

         _new_id_ = 7;
         end;
         else if _strfmt_ in ('Aug',
         'Sep') then do;

         _new_id_ = 8;
         end;
         else do;
         _new_id_ = 8;
         end;
   end;
   else if _node_id_ eq 7 then do;
         _leaf_id_ = 7;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =                    1;
         _dt_fi_17134_{1} =                    1; 
         _dt_fi_17134_{2} =                    0; 
   end;
   else if _node_id_ eq 8 then do;
         _leaf_id_ = 8;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.95652173913043;
         _dt_fi_17134_{1} =     0.04347826086956; 
         _dt_fi_17134_{2} =     0.95652173913043; 
   end;
   if _new_id_ >= 0 then do;
       _node_id_ = _new_id_;
      goto nextnode_17134;
   end;

   I_FraudFound = _tlevname_17134_{_dt_pred_lev_+1};
   label I_FraudFound = 'Into: FraudFound';
   _i_ = 1;
   _dt_predp_ = _dt_fi_17134_{_i_};
   P_FraudFoundNo = _dt_predp_;
   label P_FraudFoundNo = 'Predicted: FraudFound=No';
   _i_+1;
   _dt_predp_ = _dt_fi_17134_{_i_};
   P_FraudFoundYes = _dt_predp_;
   label P_FraudFoundYes = 'Predicted: FraudFound=Yes';
   _i_+1;
   drop _dt_predp_;
   drop _i_;
   drop _dt_pred_lev_;
   drop _dt_pred_prob_;
   drop _numval_;
   drop _node_id_;
   drop _new_id_;
   /*------------------------------------------*/
   /*_VA_DROP*/ drop 'I_FraudFound'n '_leaf_id_'n 'P_FraudFoundNo'n 'P_FraudFoundYes'n;
length 'I_FraudFound_17134_2'n $3;
      'I_FraudFound_17134_2'n='I_FraudFound'n;
'P_FraudFoundNo_17134_2'n='P_FraudFoundNo'n;
'P_FraudFoundYes_17134_2'n='P_FraudFoundYes'n;
'_leaf_id__17134_2'n='_leaf_id_'n;
   /*------------------------------------------*/